### ISSUE TITLE
[✨ Feature] Auth

### ISSUE THREAD

**Issue by cmleem** [CharmRoom/CharmRoom#19]
## 기능 개요
> 추가하려는 기능에 대한 설명
Auth 기능 추가

## 상세 내용
> 작업할 내용 TODOLIST로 작성
- [x] Spring Security 설정
- [x] 회원 가입
- [ ] 로그인/로그아웃

## 참고(선택)
> 개발에 참고하였거나 함께 보면 좋을 페이지/자료

**Comment by cmleem** [comment]
User 리포지터리에 사용자 ID를 조회하는 기능이 필요하므로 닉네임을 파라미터로 조회하도록 메서드 findByUserName을 추가하겠습니다.

**Comment by Yeop-Dong** [comment]
> User 리포지터리에 사용자 ID를 조회하는 기능이 필요하므로 닉네임을 파라미터로 조회하도록 메서드 findByUserName을 추가하겠습니다.

findByNickname이어야 하지 않을까요?

**Comment by Yeop-Dong** [comment]
> > User 리포지터리에 사용자 ID를 조회하는 기능이 필요하므로 닉네임을 파라미터로 조회하도록 메서드 findByUserName을 추가하겠습니다.
> 
> findByNickname이어야 하지 않을까요?

만약 id 기준 조회라면 findById로 하면 될것같습니다

**Comment by cmleem** [comment]
> > > User 리포지터리에 사용자 ID를 조회하는 기능이 필요하므로 닉네임을 파라미터로 조회하도록 메서드 findByUserName을 추가하겠습니다.
> > 
> > 
> > findByNickname이어야 하지 않을까요?
> 
> 만약 id 기준 조회라면 findById로 하면 될것같습니다

findByNickname으로 하겠습니다

**Comment by cmleem** [comment]
우리가 만든 엔티티인 User와 스프링 시큐리티에서 사용하는 userdeatils의 User 객체의 이름이 같음을 주의하세요

**Comment by Yeop-Dong** [comment]
> 우리가 만든 엔티티인 User와 스프링 시큐리티에서 사용하는 userdeatils의 User 객체의 이름이 같음을 주의하세요

패키지가 달라서 오류는 안날거같긴한데
많이 불편한가요?

**Comment by cmleem** [comment]
> > 우리가 만든 엔티티인 User와 스프링 시큐리티에서 사용하는 userdeatils의 User 객체의 이름이 같음을 주의하세요
> 
> 패키지가 달라서 오류는 안날거같긴한데 많이 불편한가요?

자동완성 기능때문에 제가 한참 헤매서 공유드렸습니다. 많이 불편하진 않습니다
