### ISSUE TITLE
[✨ Feature] 서비스 코드 리팩토링

### ISSUE THREAD

**Issue by cmleem** [CharmRoom/CharmRoom#58]
## 기능 개요
> 추가하려는 기능에 대한 설명
Service 레이어와 Controller 레이어 사이에 주고받을 DTO, Mapper 클래스 추가

## 상세 내용
> 작업할 내용 TODOLIST로 작성
- [x] #59
- [x] #74
- [x] Club Service Dto
- [x] #75
- [x] #76
- [x] #78
- [x] #77

## 참고(선택)
> 개발에 참고하였거나 함께 보면 좋을 페이지/자료

**Comment by Yeop-Dong** [comment]
Article, Club DTO는 제가 각각 Comment, User DTO 만들 때의 필요에 의해서  만들겠습니다.
